#!/bin/bash
#
# install - install mariacmdb 
#
function runCommand
 {
  cmd="$@"
  echo "Running command: $cmd"
  eval $cmd
  rc=$?
  if [ "$rc" != 0 ]; then
    echo "ERROR: command $cmd returned $rc"
    exit 1
  fi
 }                                         # runCommand()

function checkRepoDir
 {
  if [ ! -d $mariacmdbDir ]; then
    echo "ERROR: directory $mariacmdbDir not found"
    exit 1
  fi
 }                                         # checkRepoDir()
  
function checkCGIdir
 {
  if [ ! -d $CGIdir ]; then
    runCommand sudo mkdir /srv/www/mariacmdb
  fi
 }                                         # checkDir()
  
# main()
mariacmdbDir="$HOME/mariacmdb"             # must be cloned to home directory
CGIdir="/srv/www/mariacmdb"                # must exist
checkRepoDir                               # check the repo is in the home directory
checkCGIdir                                # check for /srv/www/mariacmdb
runCommand sudo cp $mariacmdbDir/usr/local/sbin/mariacmdb.py /usr/local/sbin
runCommand sudo cp $mariacmdbDir/usr/local/sbin/testrestapi /usr/local/sbin
runCommand sudo cp $mariacmdbDir/usr/local/sbin/serverinfo $HOME              
runCommand sudo cp $mariacmdbDir/srv/www/mariacmdb/* /srv/www/mariacmdb

