#!/bin/bash
#
# testrestapi - test various Mariacmdb RESTful APIs
#
baseURL="http://model1500/restapi.py"
let numTests=0
let numSuccesses=0
testClauses="count hostname ping query count&cpus=4&mem_gb=4 update&model100&newApp&newGroup&newOwner"
for nextClause in $testClauses; do
  let numTests=$numTests+1
  url="$baseURL?$nextClause"
  echo "Testing URL $url ..."
  curl $url 
  rc=$?
  if [ $rc != 0 ]; then                    # not successful
    echo "ERROR: curl $url returned $rc"
    break                                  # out of for loop
  fi
  let numSuccesses=$numSuccesses+1
done
if [ "$numTests" = "$numSuccesses" ]; then
  echo "All $numTests tests succeeded in $SECONDS seconds"
else
  echo "Out of $numTests tests, $numSuccesses succeeded in $SECONDS seconds"
  exit 1
fi

